language: python
matrix:
  include:
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37

before_install:
    pip install --upgrade fontTools
    pip install --upgrade jupyter

script: make test

install:
    - pip install tox

notifications:
  email: false